version: '3.8'
services:

  mysql:
    image: mysql:latest
    container_name: mysql-tt
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=tdb
    volumes:
      - mysql-data:/var/lib/mysql

  backend:
    build:
      context: ./test-task-gw
    container_name: back-end-tt-gw
    ports:
      - "3001:3000"
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_NAME=tdb
    depends_on:
      - mysql

volumes:
  mysql-data: